# Better science in less time {#bsilt}

Better science is less time is science that is more efficient, reproducible, open, inclusive, and kind. There are growing examples of better science in less time in environmental and Earth science, and beyond. Here are a few examples to showcase what is possible and being done by the community.

**Slides** that have been presented during Champions Program Cohort Calls: 

- [Better science in less time](https://docs.google.com/presentation/d/1GmuTa1sUO_boH-2TonC875pD5xvXaIMHRKIoO3vUrdY/edit?usp=sharing)
- [Empowering transformational science](https://docs.google.com/presentation/d/1SUMiQg0HhD19H-D6DDzTrFQVzub0kOINwJBG59uQCTw/edit#slide=id.p1) - [Dr. Chelle Gentemann](https://twitter.com/ChelleGentemann)

Here we also introduce the [**Pathway document**](https://drive.google.com/open?id=1X_-qPdWDCpw2F3nZr6vZnq87guyUIGLvekm0XV2H-A8) that teams will develop throughout the Champions program. The Pathway is based on Table 1 in Lowndes et al. 2017, and helps teams deliberately identify data workflow practices and next steps to facilitate efficiency and open culture in terms of reproduciblity, collaboration, communication, and culture. 

---

## Ocean Health Index: behind the scenes

Some key points to discuss from [Lowndes *et al. 2017, Nature Ecology & Evolution*: Our path to better science in less time using open data science tools](https://www.nature.com/articles/s41559-017-0160): 

- Reproducibility & communication enabled by open tooling
- Shared practices are useful beyond shared projects

If you're interested in more overview of the OHI setup, see this 2017 talk (25 mins): [OHI Better science in less time](https://www.youtube.com/watch?v=x4uzVAZvFCA)

### OHI pathway 

- Motivated by necessity
- Reimagined by possibility and community 
- Done incrementally!
- Yes: it’s an investment. 
- Also yes: huge, enduring payoff for (your) science

### Reproducibility & communication enabled by open tooling

RMarkdown to reimagine data analysis and communication. RMarkdown combines analyses & figures together, rendered to your reporting output of choice. 

An example: <http://ohi-science.org/betterscienceinlesstime/>

- Website built with R/RMarkdown & Github  
- You can get started too: ([1-hour tutorial](https://jules32.github.io/rmarkdown-website-tutorial/)) 

### Shared workflows not only useful for shared projects

- OHI team: we identified as a team & prioritized helping each other
  - We work on many different projects
  - Use same workflows, share feedback, can think together across projects
- Shared conventions reduce friction & cognitive load
  - Common ground, easier to talk about, easier to ask for help
  - You don’t need to design everything from scratch

And, critically: 

- It’s about increasing efficiency and reproducibility and open science. 
- But it is also about increasing participation and inclusion. 
- Consider diversity, equity, and inclusion in your daily practices.
- How you work and onboard others to your projects is a DEI issue. 

## Examples in the wild: environmental science

- [Regime Shifts in R & Data Science within the BC Public Service Observations from the field](https://stephhazlitt.github.io/regime-shifts/slides#1) - Stephanie Hazlitt, Government of British Columbia, slides from CascadiaRconf keynote
- [NMFSReports: Easily write NOAA reports and tech memos in R Markdown!](https://github.com/EmilyMarkowitz-NOAA/NMFSReports/blob/main/presentations/2021-06-05%20NMFSReports%20-%20R%20Cascadia%20Conf.pdf) - Emily Markowitz, NOAA Alaska Fisheries Science Center, slides from CascadiaRconf talk
- [Automated reporting in Tampa Bay with open science](https://www.openscapes.org/blog/2020/11/16/tampa-bay-reporting/) - Marcus Beck, Tampa Bay Estuary Program, Openscapes blog 
  - [TBEP's Data Management Workflow](https://tbep-tech.github.io/data-management-sop/workflow.html) and open science cake

## Further resources

### Not so standard deviation podcast 

Parker & Peng  
<http://nssdeviations.com>  
Great discussions about data concepts and “in the wild”  
[Episode 9: Spreadsheet drama](http://nssdeviations.com/episode-9-spreadsheet-drama)

### Practical computing for biologists 

Haddock & Dunn  
<http://practicalcomputing.org/>  
Software & computing concepts already on your computer  
Chapter 2: Regular expressions  


<!---

Broman, K. Initial steps toward reproducible research. http://kbroman.org/steps2rr/ (2016).

Carly Strasser

Fischetti, T. How dplyr replaced my most common r idioms. StatsBlogs http://www.onthelambda.com/2014/02/10/how-dplyr-replaced-my-most-common-r-idioms/ (10 February 2014).

--->
